# syntax=docker/dockerfile:1.6
FROM golang:1.24-alpine AS goose-builder
WORKDIR /src
RUN apk add --no-cache git
# соберёт goose в /go/bin/goose
RUN go install github.com/pressly/goose/v3/cmd/goose@v3.24.1

FROM alpine:3.19
WORKDIR /app
COPY --from=goose-builder /go/bin/goose /usr/local/bin/goose
RUN chmod +x /usr/local/bin/goose
ENTRYPOINT ["goose", "-dir", "/migrations", "postgres"]